name: Node.js CI

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
